fix smaple ioctl app, alter proc content, upd readme

diff --git a/LEDfifoLKM/ledfifo_load b/LEDfifoLKM/ledfifo_load
--- a/LEDfifoLKM/ledfifo_load
+++ b/LEDfifoLKM/ledfifo_load
@@ -1,22 +1,29 @@
 #!/bin/bash
 # REF: https://lwn.net/images/pdf/LDD3/ch03.pdf - Page 47
 
-module="ledfifo" 
+module="LEDfifoLKM" 
 device="ledfifo" 
 mode="664"
 
 # invoke insmod with all arguments we got
-# and use a pathname, as newer modutils don't look in . by default /sbin/insmod ./$module.ko $* || exit 1
+# and use a pathname, as newer modutils don't look in . by default 
+(set -x;/sbin/insmod ./$module.ko $* || exit 1)
 # remove stale nodes
-rm -f /dev/${device}[0-3]
+(set -x;rm -f /dev/${device}[0-3])
 
-major=$(awk "\\$2==\"$module\" {print \\$1}" /proc/devices)
-mknod /dev/${device}0 c $major 0
-mknod /dev/${device}1 c $major 1
-mknod /dev/${device}2 c $major 2
-mknod /dev/${device}3 c $major 3
+#major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
+major=$(cat /proc/devices | grep ${device} | cut -d' ' -f1)
+if [ -n "${major}" ]; then
+(set -x;mknod /dev/${device}0 c ${major} 0)
+#mknod /dev/${device}1 c $major 1
+#mknod /dev/${device}2 c $major 2
+#mknod /dev/${device}3 c $major 3
      
 # give appropriate group/permissions, and change the group.
-# Not all distributions have staff, some have "wheel" instead. group="staff"
+# Not all distributions have staff, some have "wheel" instead. 
+group="staff"
 grep -q '^staff:' /etc/group || group="wheel"
-chgrp $group /dev/${device}[0-3] chmod $mode /dev/${device}[0-3]
+(set -x;chgrp $group /dev/${device}[0-3] chmod $mode /dev/${device}[0-3])
+else
+echo "$0: failed to grab major node id"
+fi
